FROM quay.io/fedora/fedora-minimal:45

# Update if you need... microdnf update -y

RUN microdnf install -y python3.14 python3.14-pip && \
    python3.14 --version && \
    pip install gunicorn==23.0.0+ppc64le1 \
    --extra-index-url=https://wheels.developerfirst.ibm.com/ppc64le/linux \
    --prefer-binary && \
    pip install --no-cache-dir httpbin

EXPOSE 8080
CMD ["gunicorn", "-b", "0.0.0.0:8080", "httpbin:app"]