FROM quay.io/fedora/fedora-minimal:45

# Update if you need... microdnf update -y

RUN microdnf install -y python3.14 python3.14-pip && \
    python3.14 --version && \
    pip install --no-cache-dir httpbin gunicorn

EXPOSE 8080
CMD ["gunicorn", "-b", "0.0.0.0:8080", "httpbin:app"]