apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ocp4-numa-power-workload
  namespace: openshift-power-workload
  labels:
    app: power-numa-workload
spec:
  selector:
    matchLabels:
      app: power-numa-workload
  template:
    metadata:
      labels:
        app: power-numa-workload
    spec:
      tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      initContainers:
      - name: numa-hugepages
        image: quay.io/powercloud/ocp4-power-workload-tools:main
        imagePullPolicy: Always
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: kubernetes.io/arch
                  operator: In
                  values:
                  - ppc64le
                  - amd64
        command: [ "/bin/bash" ]
        args: [ "/report-hugepages.sh"]
        resources:
          limits:
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 100Mi
      - name: numa-numa
        image: quay.io/powercloud/ocp4-power-workload-tools:main
        imagePullPolicy: Always
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: kubernetes.io/arch
                  operator: In
                  values:
                  - ppc64le
                  - amd64
        command: [ "/bin/bash" ]
        args: [ "/report-numa.sh"]
        resources:
          limits:
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 100Mi
      containers:
      - name: numa-workload
        image: quay.io/powercloud/ocp4-power-workload-tools:main
        imagePullPolicy: Always
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: kubernetes.io/arch
                  operator: In
                  values:
                  - ppc64le
                  - amd64
        command: [ "/bin/sleep" ]
        args: [ "infinity" ]
        resources:
          limits:
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 100Mi
#        volumeMounts:
#        - name: host-sys
#          mountPath: /sys
        securityContext:
          privileged: false
          seccompProfile:
            type: RuntimeDefault
          capabilities:
# We may add this in the future
#            add:
#              - CAP_SYS_ADMIN
#              - CAP_FOWNER
#              - NET_ADMIN
#              - SYS_ADMIN
            drop:
              - ALL
#          runAsUser: 0
#          runAsGroup: 0
          runAsNonRoot: true
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
      # volumes:
      # - name: host-sys
      #   hostPath:
      #     path: /sys
      #     type: Directory
      # priorityClassName: system-cluster-critical
      hostPID: false
      hostIPC: false
      hostNetwork: false