apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: openshift-power-workload 
  namespace: openshift-power-workload

generatorOptions:
  disableNameSuffixHash: true

sortOptions:
  order: fifo

resources:
  - 00-project.yaml
  - 01-daemonset.yaml
