apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: fluentd-elasticsearch
  namespace: kube-system

generatorOptions:
  disableNameSuffixHash: true

sortOptions:
  order: fifo

resources:
  - DaemonSet.yaml
