apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ocp4-numa-power-workload-fio
  namespace: openshift-power-workload-fio
  labels:
    app: power-numa-workload-fio
spec:
  selector:
    matchLabels:
      app: power-numa-workload-fio
  template:
    metadata:
      annotations:
        openshift.io/required-scc: privileged
        openshift.io/scc: privileged
      labels:
        app: power-numa-workload-fio
    spec:
      tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      initContainers:
      - name: numa-hugepages
        image: quay.io/powercloud/ocp4-power-workload-tools:main
        imagePullPolicy: IfNotPresent
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: kubernetes.io/arch
                  operator: In
                  values:
                  - ppc64le
                  - amd64
        command: [ "/bin/bash" ]
        args: [ "/report-hugepages.sh"]
        resources:
          limits:
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 100Mi
        serviceAccount: ocp4-workload-sa
        serviceAccountName: ocp4-workload-sa
        securityContext:
          privileged: true
          capabilities:
            add:
              - CAP_SYS_ADMIN
              - CAP_FOWNER
              - NET_ADMIN
              - SYS_ADMIN
            drop:
              - ALL
          #runAsNonRoot: true
          #runAsUser: 0
          readOnlyRootFilesystem: false
          allowPrivilegeEscalation: true
      - name: numa-numa
        image: quay.io/powercloud/ocp4-power-workload-tools:main
        imagePullPolicy: IfNotPresent
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: kubernetes.io/arch
                  operator: In
                  values:
                  - ppc64le
                  - amd64
        command: [ "/bin/bash" ]
        args: [ "/report-numa.sh"]
        resources:
          limits:
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 100Mi
        serviceAccount: ocp4-workload-sa
        serviceAccountName: ocp4-workload-sa
        securityContext:
          privileged: true
          capabilities:
            add:
              - CAP_SYS_ADMIN
              - CAP_FOWNER
              - NET_ADMIN
              - SYS_ADMIN
            drop:
              - ALL
          #runAsUser: 0
          #runAsNonRoot: false
          readOnlyRootFilesystem: false
          allowPrivilegeEscalation: true
      containers:
      - name: numa-workload
        image: quay.io/powercloud/ocp4-power-workload-tools:main
        imagePullPolicy: IfNotPresent
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: kubernetes.io/arch
                  operator: In
                  values:
                  - ppc64le
                  - amd64
        command: [ "/bin/sleep" ]
        args: [ "infinity" ]
        resources:
          limits:
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 100Mi
        volumeMounts:
        - name: host-sys
          mountPath: /sys
        - name: host-dev
          mountPath: /host-dev
        - name: host-lib
          mountPath: /host-lib
        serviceAccount: ocp4-workload-sa
        serviceAccountName: ocp4-workload-sa
        securityContext:
          privileged: true
          capabilities:
            add:
              - CAP_SYS_ADMIN
              - CAP_FOWNER
              - NET_ADMIN
              - SYS_ADMIN
            drop:
              - ALL
          #runAsUser: 0
          #runAsNonRoot: false
          readOnlyRootFilesystem: false
          allowPrivilegeEscalation: true
      volumes:
       - name: host-sys
         hostPath:
           path: /sys
           type: Directory
       - name: host-dev
         hostPath:
           path: /dev
           type: Directory
       - name: host-lib
         hostPath:
           path: /lib
           type: Directory
      priorityClassName: system-cluster-critical
      hostPID: true
      hostIPC: true
      hostNetwork: true
      serviceAccount: ocp4-workload-sa
      serviceAccountName: ocp4-workload-sa