FROM quay.io/centos/centos:stream10
RUN dnf install -y numactl util-linux numactl-libs fio sysstat bpftrace perf ndctl
RUN [ "$(arch)" == "ppc64le" ]       \
    && dnf install -y powerpc-utils powerpc-utils-core bcc-tools bcc bzip2 pcp-system-tools tar python3-bcc python3 python3-pip lsvpd psmisc \
    || echo "Not running on ppc64le, skip linking powerpc dependency"
RUN [ "$(arch)" == "ppc64le" ]       \
    && python3 -m pip install -U prettytable \
    || echo "Not running on ppc64le, skip linking powerpc python dependency"
RUN [ "$(arch)" == "ppc64le" ]       \
    && sudo dnf -y install https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm \
    && sudo dnf -y install nmon \
    || echo "Not running on ppc64le, skip adding nmon"
RUN dnf update -y && dnf clean all
ADD scripts/report-hugepages.sh /
ADD scripts/report-numa.sh /
ADD scripts/run-fio.sh /
