apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: openshift-power-workload-fio
  namespace: openshift-power-workload-fio

sortOptions:
  order: fifo

resources:
- ../../fio
