FROM golang:1.26 as builder

WORKDIR /src
RUN curl -O -L https://raw.githubusercontent.com/jimmidyson/configmap-reload/refs/heads/main/configmap-reload.go \
    && curl -O -L https://raw.githubusercontent.com/jimmidyson/configmap-reload/refs/heads/main/go.mod \
    && curl -O -L https://raw.githubusercontent.com/jimmidyson/configmap-reload/refs/heads/main/go.sum 
RUN CGO_ENABLED=0 GOARCH=ppc64le go build --installsuffix cgo -ldflags="-s -w -extldflags '-static'" -a -o /configmap-reload configmap-reload.go

FROM gcr.io/distroless/static-debian13:nonroot
LABEL org.opencontainers.image.source="https://github.com/jimmidyson/configmap-reload"
USER 65534
COPY --from=builder /configmap-reload /configmap-reload
ENTRYPOINT ["/configmap-reload"]