FROM quay.io/fedora/fedora-minimal:45

# Install only PHP CLI
RUN microdnf install -y python3.13 python-pip && \
    python3.13 --version

COPY main.py .
USER 0
RUN chmod 755 main.py
EXPOSE 80
USER 1001
CMD ["python3", "main.py"]