apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: workloads-pvc
  namespace: openshift-power-workload
spec:
  storageClassName: "ibm-spectrum-scale-data-rwo-sc"
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 4000Gi
  volumeName: workloads-pv