apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: openshift-power-workload-fio 
  namespace: openshift-power-workload-fio

generatorOptions:
  disableNameSuffixHash: true

sortOptions:
  order: fifo

resources:
  - 00-project.yaml
  - 01-sa.yaml
  - 02-rbac.yaml
  - 03-pvc.yaml
  - 04-daemonset.yaml
