apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nx-gzip-ds
  namespace: nx-gzip-demo
  labels:
    app: power-nx-gzip-workload
spec:
  selector:
    matchLabels:
      app: power-nx-gzip-workload
  template:
    metadata:
      annotations:
        io.kubernetes.cri-o.Devices: /dev/crypto/nx-gzip
      labels:
        app: power-nx-gzip-workload
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/worker
                operator: Exists
              - key: node-role.kubernetes.io/control-plane
                operator: DoesNotExist
      containers:
      - name: nx-gzip-workload
        image: quay.io/powercloud/ocp4-power-workload-tools:main
        imagePullPolicy: IfNotPresent
        command: [ "/bin/sleep" ]
        args: [ "infinity" ]
        resources:
          limits:
            memory: 4000Mi
          requests:
            cpu: 4
            memory: 4000Mi
        serviceAccount: nx-gzip-sa
        serviceAccountName: nx-gzip-sa
        securityContext:
          privileged: false
          capabilities:
            drop:
              - ALL
          readOnlyRootFilesystem: false
          allowPrivilegeEscalation: false
      serviceAccount: nx-gzip-sa
      serviceAccountName: nx-gzip-sa