apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ocp4-nx-gzip-power-workload
  namespace: nx-gzip
  labels:
    app: power-nx-gzip-workload
spec:
  selector:
    matchLabels:
      app: power-nx-gzip-workload
  template:
    metadata:
      annotations:
        io.kubernetes.cri-o.Devices: /dev/crypto/nx-gzip
      labels:
        app: power-nx-gzip-workload
    spec:
      containers:
      - name: nx-gzip-workload
        image: quay.io/powercloud/ocp4-power-workload-tools:main
        imagePullPolicy: IfNotPresent
        command: [ "/bin/sleep" ]
        args: [ "infinity" ]
        resources:
          limits:
            memory: 4000Mi
          requests:
            cpu: 4
            memory: 4000Mi
        serviceAccount: ocp4-workload-sa
        serviceAccountName: ocp4-workload-sa
        securityContext:
          privileged: false
          capabilities:
            drop:
              - ALL
          #runAsUser: 0
          #runAsNonRoot: false
          readOnlyRootFilesystem: false
          allowPrivilegeEscalation: false
      serviceAccount: ocp4-workload-sa
      serviceAccountName: ocp4-workload-sa