apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: nx-gzip 
  namespace: nx-gzip

generatorOptions:
  disableNameSuffixHash: true

sortOptions:
  order: fifo

resources:
  - 00-project.yaml
  - 01-daemonset.yaml
