# Build Stage: using Go 1.25.0 image
## Pure Go build, no CGO required
FROM quay.io/projectquay/golang:1.25 AS builder

WORKDIR /workspace

RUN curl -O -L https://github.com/llm-d/llm-d-inference-sim/archive/refs/tags/v0.8.2.zip && \
    dnf install unzip -y && \
    unzip v0.8.2.zip

WORKDIR /workspace/llm-d-inference-sim-0.8.2

# cache deps before building and copying source so that we don't need to re-download as much
# and so that source changes don't invalidate our downloaded layer
RUN go mod download

RUN cp cmd/llm-d-inference-sim/main.go cmd/cmd.go

# Build simulator, no Python, no embedded tokenizer, no CGO for ZMQ, use pure Go
# The default kv-cache build uses UDS tokenizer (//go:build !embedded_tokenizers)
RUN CGO_ENABLED=0 GOOS=linux go build -o bin/llm-d-inference-sim ./cmd/cmd.go

FROM registry.access.redhat.com/ubi10/ubi-micro:latest

WORKDIR /

COPY --from=builder /workspace/llm-d-inference-sim-0.8.2/bin/llm-d-inference-sim /app/llm-d-inference-sim

USER 65532:65532

ENTRYPOINT ["/app/llm-d-inference-sim"]
