FROM registry.access.redhat.com/ubi10/ubi-micro:latest

WORKDIR /

ADD tmp/llm-d-inference-sim-0.8.2/bin/llm-d-inference-sim-* /app/

RUN mv tmp/llm-d-inference-sim-0.8.2/bin/llm-d-inference-sim-$(arch) llm-d-inference-sim

USER 65532:65532

ENTRYPOINT ["/app/llm-d-inference-sim"]