---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ocp4-data-pv
  namespace: openshift-power-workload
  labels:
    type: local
spec:
  storageClassName: ocp4-data
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce 
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-pvc
  namespace: openshift-power-workload
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: ocp4-data