apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ocp4-net-power-workload
  namespace: openshift-net-workload
  labels:
    app: power-net-workload
spec:
  replicas: 2
  selector:
    matchLabels:
      app: power-net-workload
  template:
    metadata:
      labels:
        app: power-net-workload
    spec:
      tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      nodeSelector:
        kubernetes.io/arch: ppc64le
      containers:
      - name: agnhost
        image: registry.k8s.io/e2e-test-images/agnhost:2.45
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          type: TCP
        command: [ "/agnhost" ]
        args: [ "nettest", "--port", "8080" ]
        resources:
          limits:
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 100Mi
        securityContext:
          privileged: false
          seccompProfile:
            type: RuntimeDefault
          capabilities:
            drop:
              - ALL
          runAsNonRoot: true
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
      hostPID: false
      hostIPC: false
      hostNetwork: false