apiVersion: v1
kind: Pod
metadata:
  name: runner
  labels:
    app: power-net-workload
spec:
  containers:
    - name: runner
      image: quay.io/centos/centos:stream9
      imagePullPolicy: Always
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - ppc64le
      command: ["/bin/sleep"]
      args: ["infinity"]
      resources:
        limits:
          memory: 100Mi
        requests:
          cpu: 100m
          memory: 100Mi
      securityContext:
        privileged: false
        seccompProfile:
          type: RuntimeDefault
        capabilities:
          drop:
            - ALL
        runAsNonRoot: true
        readOnlyRootFilesystem: true
        allowPrivilegeEscalation: false
