apiVersion: v1
kind: Service
metadata:
  name: power-net-workload-svc
spec:
  type: NodePort
  selector:
    app: power-net-workload
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30007